language: clojure
lein: lein2
script: lein2 all test
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
branches:
  only:
    - master

addons:
# Fix OpenJDK builds
# https://github.com/travis-ci/travis-ci/issues/5227
  hostname: short-hostname
